import type { Order, Customer, Document, Delivery, CourierOrder } from "@/types/models"

// Sample orders data
export const sampleOrders: Order[] = [
  {
    id: "PO-2024-001",
    poNumber: "PO001",
    supplier: "Supplier A",
    importer: "Acme Corp",
    status: "Completed",
    cargoStatus: "delivered",
    freightType: "Sea Freight",
    totalValue: 12500,
    customerName: "Acme Corporation",
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "PO-2024-002",
    poNumber: "PO002",
    supplier: "Supplier B",
    importer: "Global Traders",
    status: "In Progress",
    cargoStatus: "in-transit",
    freightType: "Air Freight",
    totalValue: 8750,
    customerName: "Global Enterprises",
    createdAt: "2024-01-20T14:45:00Z",
  },
  {
    id: "PO-2024-003",
    poNumber: "PO003",
    supplier: "Supplier C",
    importer: "Tech Innovators",
    status: "Pending",
    cargoStatus: "instruction-sent",
    freightType: "Sea Freight",
    totalValue: 15000,
    customerName: "Tech Solutions",
    createdAt: "2024-01-25T09:15:00Z",
  },
]

// Sample customers data
export const sampleCustomers: Customer[] = [
  {
    id: "CUST-001",
    name: "Acme Corp",
    contactPerson: "John Doe",
    email: "john.doe@example.com",
    phone: "+27 11 123 4567",
    address: {
      street: "123 Main Street",
      city: "Johannesburg",
      postalCode: "2000",
      country: "South Africa",
    },
    totalOrders: 15,
    totalSpent: 187500,
  },
  {
    id: "CUST-002",
    name: "Global Traders",
    contactPerson: "Alice Smith",
    email: "alice.smith@example.com",
    phone: "+27 21 987 6543",
    address: {
      street: "456 Ocean View Drive",
      city: "Cape Town",
      postalCode: "8000",
      country: "South Africa",
    },
    totalOrders: 8,
    totalSpent: 68000,
  },
  {
    id: "CUST-003",
    name: "Tech Innovators",
    contactPerson: "Bob Johnson",
    email: "bob.johnson@example.com",
    phone: "+27 31 555 1212",
    address: {
      street: "789 Innovation Lane",
      city: "Durban",
      postalCode: "4000",
      country: "South Africa",
    },
    totalOrders: 12,
    totalSpent: 240000,
  },
]

// Sample documents data
export const documents: Document[] = [
  {
    id: "DOC-001",
    name: "Invoice_PO001.pdf",
    type: "Invoice",
    url: "/path/to/invoice.pdf",
    order_id: "PO001",
    created_at: "2023-07-01T08:00:00Z",
  },
  {
    id: "DOC-002",
    name: "Shipping_Manifest_PO002.pdf",
    type: "Shipping Document",
    url: "/path/to/shipping_manifest.pdf",
    order_id: "PO002",
    created_at: "2023-07-05T14:30:00Z",
  },
  {
    id: "DOC-003",
    name: "Customs_Declaration_PO003.pdf",
    type: "Customs Form",
    url: "/path/to/customs_declaration.pdf",
    order_id: "PO003",
    created_at: "2023-07-10T11:15:00Z",
  },
]

// Sample deliveries data
export const deliveries: Delivery[] = [
  {
    id: "DEL-001",
    orderNumber: "ORD-001",
    status: "In Transit",
    estimatedDelivery: "2023-07-20",
    driverName: "John Smith",
    deliveryCompany: "FastTrack Logistics",
    poNumber: "PO001",
  },
  {
    id: "DEL-002",
    orderNumber: "ORD-002",
    status: "Delivered",
    estimatedDelivery: "2023-07-25",
    actualDelivery: "2023-07-24",
    driverName: "Alice Johnson",
    deliveryCompany: "Swift Deliveries",
    poNumber: "PO002",
  },
  {
    id: "DEL-003",
    orderNumber: "ORD-003",
    status: "Pending",
    estimatedDelivery: "2023-07-30",
    driverName: "Bob Williams",
    deliveryCompany: "Reliable Transport",
    poNumber: "PO003",
  },
]

// Sample courier orders data
export const courierOrders: CourierOrder[] = [
  {
    id: "CO-001",
    waybillNo: "WB001",
    poNumber: "PO001",
    createdAt: "2023-11-01T10:00:00Z",
    sender: "Acme Corp",
    receiver: "Beta Ltd",
    fromLocation: "Johannesburg",
    toLocation: "Cape Town",
    status: "Delivered",
    serviceType: "Express",
  },
  {
    id: "CO-002",
    waybillNo: "WB002",
    poNumber: "PO002",
    createdAt: "2023-11-05T14:30:00Z",
    sender: "Gamma Inc",
    receiver: "Delta Co",
    fromLocation: "Durban",
    toLocation: "Pretoria",
    status: "In Transit",
    serviceType: "Standard",
  },
  {
    id: "CO-003",
    waybillNo: "WB003",
    poNumber: "PO003",
    createdAt: "2023-11-10T08:45:00Z",
    sender: "Epsilon Ltd",
    receiver: "Zeta Corp",
    fromLocation: "Cape Town",
    toLocation: "Port Elizabeth",
    status: "Pending",
    serviceType: "Economy",
  },
]

// Sample estimates data
export const estimates = [
  {
    id: "EST-001",
    customerId: "CUST-001",
    customerName: "Acme Corporation",
    customerEmail: "contact@acmecorp.com",
    status: "Draft",
    createdAt: "2024-03-01T09:30:00Z",
    updatedAt: "2024-03-01T10:15:00Z",
    freightType: "Air Freight",
    commercialValue: "100000",
    customsDuties: "9250",
    handlingFees: "4625",
    shippingCost: "18500",
    documentationFee: "250",
    communicationFee: "150",
    notes: "Priority shipment for manufacturing equipment",
    totalAmount: 37273.46,
  },
  {
    id: "EST-002",
    customerId: "CUST-002",
    customerName: "Global Enterprises",
    customerEmail: "info@globalent.com",
    status: "Sent",
    createdAt: "2024-03-02T14:20:00Z",
    updatedAt: "2024-03-02T15:45:00Z",
    freightType: "Sea Freight",
    commercialValue: "250000",
    customsDuties: "22500",
    handlingFees: "8750",
    shippingCost: "32000",
    documentationFee: "350",
    communicationFee: "200",
    notes: "Bulk shipment of raw materials",
    totalAmount: 85625.75,
  },
  {
    id: "EST-003",
    customerId: "CUST-003",
    customerName: "Tech Solutions",
    customerEmail: "orders@techsolutions.co.za",
    status: "Accepted",
    createdAt: "2024-02-28T11:10:00Z",
    updatedAt: "2024-03-01T09:30:00Z",
    freightType: "Air Freight",
    commercialValue: "75000",
    customsDuties: "6800",
    handlingFees: "3200",
    shippingCost: "12500",
    documentationFee: "250",
    communicationFee: "150",
    notes: "Fragile electronic components",
    totalAmount: 27892.5,
  },
  {
    id: "EST-004",
    customerId: "CUST-004",
    customerName: "Innovative Industries",
    customerEmail: "procurement@innovative.co.za",
    status: "Rejected",
    createdAt: "2024-02-25T16:40:00Z",
    updatedAt: "2024-02-26T10:20:00Z",
    freightType: "Sea Freight",
    commercialValue: "120000",
    customsDuties: "11000",
    handlingFees: "5500",
    shippingCost: "22000",
    documentationFee: "300",
    communicationFee: "180",
    notes: "Client requested lower pricing",
    totalAmount: 44385.25,
  },
  {
    id: "EST-005",
    customerId: "CUST-005",
    customerName: "Prime Logistics",
    customerEmail: "orders@primelogistics.com",
    status: "Draft",
    createdAt: "2024-03-03T08:50:00Z",
    freightType: "Sea Freight",
    commercialValue: "85000",
    customsDuties: "7800",
    handlingFees: "3800",
    shippingCost: "15000",
    documentationFee: "280",
    communicationFee: "170",
    notes: "New customer special rate",
    totalAmount: 31452.75,
  },
]
